# Generated by Django 4.2.24 on 2025-09-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoiapp',
            name='availability',
            field=models.TextField(blank=True, help_text='Tutor availability provided via EOI', null=True),
        ),
        migrations.AddField(
            model_name='eoiapp',
            name='preference',
            field=models.IntegerField(default=0, help_text='Coordinator-set priority (1 = highest, 2 = next, etc.)'),
        ),
        migrations.AddField(
            model_name='eoiapp',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Tutor qualifications provided via EOI', null=True),
        ),
    ]
