# Generated by Django 4.2.24 on 2025-09-14 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('import_type', models.CharField(choices=[('eoi', 'EOI (Casual Master/EOI spreadsheet)'), ('master_classes', 'Master Class List'), ('tutorial_allocations', 'Tutorial Allocations')], max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_ok', models.PositiveIntegerField(default=0)),
                ('rows_error', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
