# Generated by Django 4.2.23 on 2025-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="campus_name",
            field=models.CharField(
                choices=[
                    ("HOBART", "Hobart"),
                    ("LAUNCESTON", "Launceston"),
                    ("ONLINE", "Online"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
