# Generated by Django 4.2.23 on 2025-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_campus_campus_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="campus_name",
            field=models.CharField(
                choices=[("SB", "Hobart"), ("IR", "Launceston"), ("ONLINE", "Online")],
                max_length=20,
                unique=True,
            ),
        ),
    ]
